### ISSUE TITLE
无法访问根目录, 必须指定访问 /index.html 才行.

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/serverless-website#28]
![image](https://user-images.githubusercontent.com/16363180/168224240-e62cbb95-9082-4985-bf2f-ff8414290e0a.png)

![image](https://user-images.githubusercontent.com/16363180/168224292-b509e190-d145-496b-9801-fa8c298d8896.png)

**Comment by anycodes** [comment]
已修复。
